name: fullcert
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.5
  - pip=22.2
  - pytorch=1.12.0
  - torchvision=0.13.0
  - numpy=1.23.1
  - tqdm=4.64.0
  - matplotlib=3.5.2
  - scikit-learn=1.1.1
  - typeguard=2.13.0
  - pytest=7.1.2
  - tensorboard=2.9.1
  - seaborn=0.12.0
  - scipy=1.8.1
